import { Injectable, signal, WritableSignal } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class Audio {
  // per l'audio
  private ctx: AudioContext | null = null;
  // fonte
  private source: AudioBufferSourceNode | OscillatorNode | null = null;
  // suono attivo
  isPlaying: WritableSignal<string> = signal<string>('');


  play(type: 'rain' | 'white-noise' | 'lofi') {
    // se suona già qualcosa lo fermo
    this.stop();
    this.ctx = new AudioContext();

    // per ogni tipo chiamo il metodo differente
    switch (type) {
      case 'rain':
        this.source = this.playBrownNoise(this.ctx)
        // aggiorno l'attuale
        this.isPlaying.set('rain')
        break
      case 'white-noise':
        this.source = this.playWhiteNoise(this.ctx)
        this.isPlaying.set('white-noise')
        break
      case 'lofi':
        this.source = this.playLofi(this.ctx)
        this.isPlaying.set('lofi')
        break
    }
  }


  stop() {
    // stoppo tutto
    this.source?.stop()
    this.ctx?.close()
    // "azzero" tutto
    this.source = null;
    this.ctx = null;
    this.isPlaying.set('');
  }

  // METODI PER MUSICA
  // generated by @Claude.ai

  playWhiteNoise(ctx: AudioContext) {
    const buffer = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    for (let i = 0; i < data.length; i++) {
      data[i] = Math.random() * 2 - 1; // valori casuali tra -1 e 1
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.loop = true;
    source.connect(ctx.destination);
    source.start();
    return source; // lo salvi per poterlo stoppare dopo
  }

  playBrownNoise(ctx: AudioContext) {
    const buffer = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate);
    const data = buffer.getChannelData(0);
    let last = 0;
    for (let i = 0; i < data.length; i++) {
      const white = Math.random() * 2 - 1;
      data[i] = (last + (0.02 * white)) / 1.02;
      last = data[i];
      data[i] *= 3.5; // amplifica
    }
    const source = ctx.createBufferSource();
    source.buffer = buffer;
    source.loop = true;
    source.connect(ctx.destination);
    source.start();
    return source;
  }

  playLofi(ctx: AudioContext) {
    const oscillator = ctx.createOscillator();
    const filter = ctx.createBiquadFilter();
    const gain = ctx.createGain();

    oscillator.type = 'sawtooth';
    oscillator.frequency.setValueAtTime(60, ctx.currentTime);
    filter.type = 'lowpass';
    filter.frequency.setValueAtTime(400, ctx.currentTime);
    gain.gain.setValueAtTime(0.1, ctx.currentTime);

    oscillator.connect(filter);
    filter.connect(gain);
    gain.connect(ctx.destination);
    oscillator.start();
    return oscillator;
  }

}
